// LOCALHOST 

### Get all the movies
GET http://localhost:8080/movies 

### Get movies by ID
GET http://localhost:8080/movies/633487e1bbb0af0db7454cb4
### 
GET http://localhost:8080/movies/633487e1bbb0af0db7454cb5 
### 
GET http://localhost:8080/movies/633487e1bbb0af0db7454cb6

### Create Movie 
POST http://localhost:8080/movies HTTP/1.1
content-type: application/json

{
"movieTitle":"Saving Private Ryan", 
"movieAuhorName":"Steven", 
"movieAuhorLastName":"Spielberg", 
"movieGenre":"War", 
"movieYear":"1998"
}

### PUT movies 
PUT http://localhost:8080/movies/633487e1bbb0af0db7454cb4 HTTP/1.1
content-type: application/json

{
"movieTitle":"Troy", 
"movieAuhorName":"Wolfgang", 
"movieAuhorLastName":"Petersen", 
"movieGenre":"Epic", 
"movieYear":"2004"
}

### DELETE movies
DELETE http://localhost:8080/movies/63348ecdfd225624b0616b02 HTTP/1.1


// PRODUCTION Deploy 
### Get all the movies
GET https://web-service-cse-341-movies-plus.onrender.com/movies

### Get movies by ID
GET https://web-service-cse-341-movies-plus.onrender.com/movies/633487e1bbb0af0db7454cb4
### 
GET https://web-service-cse-341-movies-plus.onrender.com/movies/633487e1bbb0af0db7454cb5
### 
GET https://web-service-cse-341-movies-plus.onrender.com/movies/633487e1bbb0af0db7454cb6

### Create movie
POST https://web-service-cse-341-movies-plus.onrender.com/movies HTTP/1.1
content-type: application/json

{
"movieTitle":"Saving Private Ryan", 
"movieAuhorName":"Steven", 
"movieAuhorLastName":"Spielberg", 
"movieGenre":"War", 
"movieYear":"1998"
}

### PUT movies
PUT https://web-service-cse-341-movies-plus.onrender.com/movies/632cb07ae4c970f823ee6f5f HTTP/1.1
content-type: application/json

{
"firstName":"Azahara", 
"lastName":"Soler", 
"email":"azahara@test.com", 
"favoriteColor":"Red", 
"birthday":"30/12/1991"
}

### DELETE movies
DELETE https://web-service-cse-341-movies-plus.onrender.com/movies/632f52e8ff1d3c65c218cccb HTTP/1.1
